# Импорт библиотеки NumPy

In [1]:
import numpy as np

# Создание массива из списка

In [2]:
a = np.array([1,2,3,4,5])
b = np.array(range(1,7)) # альтернативный способ создания массива
print(a)
print(type(a))
print(np.shape(a))
print(b)
print(type(b))
print(np.shape(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


# Создание многомерного массива (матрицы)

In [3]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b)
print(type(b))
print(np.shape(b))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


# Создание матрицы нулей 

In [4]:
a = np.zeros((5,5))
print(a)
print(type(a))
print(np.shape(a))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
<class 'numpy.ndarray'>
(5, 5)


# Создание массива единиц

In [5]:
a = np.ones((4,3)) 
print(a)
print(type(a))
print(np.shape(a))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
<class 'numpy.ndarray'>
(4, 3)


# Создание единичной матрицы

In [6]:
a = np.eye(5,5) 
print(a)
print(type(a))
print(np.shape(a))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
<class 'numpy.ndarray'>
(5, 5)


# Создание незаполненного (заполненного мусором) массива

In [7]:
a = np.empty((3,3,3)) 
print(a)
print(type(a))
print(np.shape(a))

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
<class 'numpy.ndarray'>
(3, 3, 3)


# Создание массива из последовательности чисел numpy

In [8]:
a = np.arange(9,0,-1.5) # создание последовательности
print(a)
b = np.array([a,a]) # создание двумерного массива из последовательности
print(b)

[9.  7.5 6.  4.5 3.  1.5]
[[9.  7.5 6.  4.5 3.  1.5]
 [9.  7.5 6.  4.5 3.  1.5]]


# Создание массива, заполненного inf

In [9]:
a = np.full((2,2), np.inf) 
print(a)
print(type(a))
print(np.shape(a))

[[inf inf]
 [inf inf]]
<class 'numpy.ndarray'>
(2, 2)


# Демонстрация аттрибутов для массива

In [10]:
a = np.full((2,2), 15) # заполненый числом 15 массив
print(a)
print(type(a))
print(np.shape(a))
print(a.dtype)

[[15 15]
 [15 15]]
<class 'numpy.ndarray'>
(2, 2)
int64


# Примеры индексирования и срезов

In [11]:
a = np.array([2,1,3,6,5,3,8,71]) # одномерный массив
print(a)
print(a[4]) # получение отдельного элемента
print(a[1:4]) # получение подмассива элементов с помощью среза



[ 2  1  3  6  5  3  8 71]
5
[1 3 6]


In [12]:
b = np.array([[2,1,3], 
            [6,10,5],
            [4,7,71]]) # двумерный массив
print(b)
print(b[2,1]) # второй столбец третья строка
print(b[[0,2]]) # выбор первой и третьей строки из матрицы

[[ 2  1  3]
 [ 6 10  5]
 [ 4  7 71]]
7
[[ 2  1  3]
 [ 4  7 71]]


In [13]:
print(b[0:2]) # срез с первой по вторую строку матрицы
print(b[0:2,0:2]) # срез с первой строки по вторую строку и с первого столбца по второй столбец

[[ 2  1  3]
 [ 6 10  5]]
[[ 2  1]
 [ 6 10]]


In [14]:
b[2][2] # другой способ индексирования

np.int64(71)

In [15]:
b[:,2] # весь третий столбец

array([ 3,  5, 71])

In [16]:
b[:2] # первая и вторая строка

array([[ 2,  1,  3],
       [ 6, 10,  5]])

In [17]:
b[...,2] # то же самое, что и [:,2]

array([ 3,  5, 71])

# Примеры векторных операций и базовых статистик

In [18]:
a = np.array([[1,2,3], 
            [4,6,8],
            [9,25,12]])
b = np.array([[1,9,2], 
            [1,6,8,],
            [1,0,1]])

In [19]:
print(a + b) # поэлементное сложение массивов

[[ 2 11  5]
 [ 5 12 16]
 [10 25 13]]


In [20]:
print(a * b) # поэлементное умножение массивов

[[ 1 18  6]
 [ 4 36 64]
 [ 9  0 12]]


In [21]:
print(a ** b) # поэлементное возведение массива a в степень b (элементов a в степень элементов b)

[[       1      512        9]
 [       4    46656 16777216]
 [       9        1       12]]


In [22]:
print(a.sum()) # сумма элементов массива a

70


In [23]:
print(b.mean()) # вычисление средней величины массива b

3.2222222222222223


In [24]:
print(b.std()) # вычисление стандартного отклонения массива b

3.2584173996922625
